# Generated by Django 3.1.6 on 2021-02-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
