# Generated by Django 3.1.6 on 2021-02-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
