# Generated by Django 3.1.6 on 2021-02-05 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamesite', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('commentText', models.TextField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
